### DISCUSSION TITLE
The color is missing from my log messages. Why?

### DISCUSSION THREAD

**Discussion by NadChel** [apache/logging-log4j2#1735] [Q&A] [answered]
Why doesn't this log4j configuration work? I mean the log messages themselves are correct, but the color is missing. The messages are all white, even, for example, `WARN` messages that are supposed to be in yellow
```yml
Configuration:

  Appenders:
    Console:
      name: CONSOLE
      PatternLayout:
        pattern: "%highlight{%d{DATE}%n%-5p [%t] : %m%n}"
      target: SYSTEM_OUT
    File:
      name: FILE
      PatternLayout:
        pattern: "%highlight{%d{DATE}%n%-5p [%t] : %m%n}"
      fileName: "src/main/resources/log.txt"
      append: false
  Loggers:
    Root:
      level: info
      AppenderRef:
         - ref: FILE
         - ref: CONSOLE
```
My logging dependency is this (I put an `@Slf4j` annotation from the Lombok library):
```xml
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-slf4j2-impl</artifactId>
            <version>2.20.0</version>
        </dependency>
```
Example message (it's in white):
```
26 авг. 2023 02:43:30,917
WARN  [AWT-EventQueue-0] : Bass Drum is not found in the current instrument map – the sound may not fully match the pattern
```

**Comment by ppkarwasz** [comment, marked as answer]
You are probably using Windows. Since by default `cmd.exe` does not support ANSI escapes, they are disabled on Windows and enabled on all other platforms.

To enable Log4j's support for ANSI escapes on Windows you need to:
 * either set `disableAnsi` to false in your layout:
    ```yaml
   PatternLayout:
       disableAnsi: false
       pattern: "%highlight{%d{DATE}%n%-5p [%t] : %m%n}"
    ```
 * or set the system property `log4j2.skipJansi` to `false`.
 
 **Remark**: If you are using `cmd.exe`, ANSI escape sequences will not be converted into colors unless:
  * you set `VirtualTerminalLevel` to 1 (see [this SO question](https://stackoverflow.com/q/16755142/11748454))
  * or you add Jansi 1.x to your classpath.
