### DISCUSSION TITLE
JsonTemplateLayout eventTemplateUri from spring cloud config

### DISCUSSION THREAD

**Discussion by paulmarcelinbejan** [apache/logging-log4j2#2536] [Q&A] [answered]
I have configured my application to log as JSON using log4j2 configuration:

```
Configuration:

  status: warn

  Appenders:
    Console:
      name: CONSOLE
      target: SYSTEM_OUT
      JsonTemplateLayout:
        eventTemplateUri: "classpath:log4j2/templates/jsonLayout.json"

  Loggers:
    Root:
      level: INFO
      AppenderRef:
        - ref: CONSOLE
```

at the moment I'm using a file in the classpath (as configured on property Configuration.Appenders.Console.JsonTemplateLayout.eventTemplateUri), but since I have a [cloud config server](https://docs.spring.io/spring-cloud-config/docs/current/reference/html/), I would like to move that file into the cloud config server to be centralized and used by all microservices.

is there a feature to retrieve the file from url ? like I'm doing for `logging.config` since I'm using

`logging.config: http://config-provider:8888/config/coanda-airlines-config-provider/application-config-log-json.yaml`
