### ISSUE TITLE
JSON pretty print is not working in JsonTemplateLayout latest version log4j-layout-template-json 2.23.1

### ISSUE THREAD

**Issue by pSinghDelaplex** [apache/logging-log4j2#2624]
## Description

[A clear and concise description of what the bug is.]

## Configuration

**Version:** [Log4j version]

**Operating system:** [OS and version]

**JDK:** [JDK distribution and version]

## Logs

```
[Stacktraces, errors, etc. relevant applications logs.]
```

## Reproduction

[An isolated test reproducing the test.
JUnit tests similar to the ones in the code base are extremely appreciated.]

**Comment by vy** [comment]
@pSinghDelaplex, JTL never had pretty-printing, and [it is already documented](https://logging.apache.org/log4j/2.x/manual/json-template-layout.html#features), hence I am not able to understand the problem here. Please provide more information.

**Comment by pSinghDelaplex** [comment]
log4j2-jsontemplatelayout-log-message-field-as-json

In my log I get this

```
{
"@timestamp": "2024-05-26T10:52:56.100Z","ecs.version": "1.2.0","log.level": "INFO","message": "{appId=1234, action=Payment Received}","process.thread.name": "main", "log.logger": "INFO"
}
```

But I want the message to be in JSON, so would like:

```
{
	"@timestamp": "2024-05-26T10:52:56.100Z",
	"ecs.version": "1.2.0",
	"log.level": "INFO",
	"message": {
		"appId": "1234",
		"action": "Payment Received"
	},
	"process.thread.name": "main",
	"log.logger": "INFO"
}
```

**Comment by vy** [comment]
JTL doesn't support pretty-printing, and for a reason: performance. JSON output is expected to be delivered to a log ingestion end point, not read by human. _For tests and local development_, you can set up Log4j to use `PatternLayout` instead. (JTL is a very good choice for production, keep it that way!)

**Comment by pSinghDelaplex** [comment]
Hey @vy ,Got your point but there is a query I have complete json object and in it I have message field which has JSON within the string . **is there any way in JsonTemplateLayout where i can only have filtered nested json from the message ?**

`**{"@timestamp": "2024-05-26T10:52:56.100Z","ecs.version": "1.2.0","log.level": "INFO", "message": "Service 1 -> 127.0.0.1:\r\n{\"appId\":\"1234\", \"action\":\"Payment Received\"}","process.thread.name": "http-nio-0.0.0.0-59078-exec-1", "log.logger": "com.example"}**`

**Comment by vy** [comment]
> is there any way in JsonTemplateLayout where i can filtered json from the string message field along with whole json log

@pSinghDelaplex, I am not able to follow what you mean. You share the following JSON-formatted log event:

```
{"@timestamp": "2024-05-26T10:52:56.100Z","ecs.version": "1.2.0","log.level": "INFO", "message": "Service 1 -> 127.0.0.1:\r\n{\"appId\":\"1234\", \"action\":\"Payment Received\"}","process.thread.name": "http-nio-0.0.0.0-59078-exec-1", "log.logger": "com.example"}
```

Here, the `message` field contains the following value:

```
Service 1 -> 127.0.0.1:\r\n{\"appId\":\"1234\", \"action\":\"Payment Received\"}
```

This is **not** a valid JSON at all.

**Can you give an example of how the formatted log event should look like?**

**Comment by vy** [comment]
@pSinghDelaplex, can you also share the following information, please?

1. `pom.xml`
2. Log4j configuration (e.g., `log4j2.xml`)
3. The log event template used in JSON Template Layout

**Comment by pSinghDelaplex** [comment]
Hi @vy 

build.gradle

```
  implementation("org.springframework.boot:spring-boot-starter-log4j2")
  implementation("org.apache.logging.log4j:log4j-layout-template-json:2.23.1")
```

log4j-spring.yml

```
Configuration:
  status: warn
  name: Default
  monitorInterval: 30
  Properties:
    property:
      - name: log-path
        value: "../logs"
  Appenders:
    Console:
      name: Console_Appender
      target: SYSTEM_OUT
      JsonTemplateLayout:
        eventTemplateUri: classpath:EcsLayout.json
        eventTemplateAdditionalField:
          - key: "message"
            value: '{"$resolver": "message", "field": "name"}'
            format: "JSON"
    RollingFile:
      - name: RollingFile_Appender
        fileName: ${log-path}/${sys:LOG_FILE}
        filePattern: "${log-path}/${sys:LOG_FILE}.%d{yyyy-MM-dd}T%d{HH-mm-ss}.%i.log"
        JsonTemplateLayout:
          eventTemplateUri: classpath:EcsLayout.json
          eventTemplateAdditionalField:
            - key: "message"
              value: '{"$resolver": "message", "field": "name"}'
              format: "JSON"
        Policies:
          SizeBasedTriggeringPolicy:
            size: 20 MB
        DefaultRollOverStrategy:
          Delete:
            basePath: ${log-path}
            maxDepth: 1
            IfFileName:
              glob: "${sys:LOG_FILE}.*.log"
              IfAccumulatedFileCount:
                exceeds: 10
  Loggers:
    Root:
      level: all
      AppenderRef:
        - ref: Console_Appender
          level: info
        - ref: RollingFile_Appender
          level: info
    Logger:
      - name: org.springframework.web.servlet.DispatcherServlet
        level: all
        additivity: false
        AppenderRef:
          - ref: Console_Appender
          - ref: RollingFile_Appender
```

EcsLayout.json

```
{
  "@timestamp": {
    "$resolver": "timestamp",
    "pattern": {
      "format": "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'",
      "timeZone": "UTC"
    }
  },
  "ecs.version": "1.2.0",
  "log.level": {
    "$resolver": "level",
    "field": "name"
  },
  "message": {
    "$resolver": "message",
    "stringified": false
  },
  "process.thread.name": {
    "$resolver": "thread",
    "field": "name"
  },
  "log.logger": {
    "$resolver": "logger",
    "field": "name"
  },
  "labels": {
    "$resolver": "mdc",
    "flatten": true,
    "stringified": true
  },
  "tags": {
    "$resolver": "ndc"
  },
  "error.type": {
    "$resolver": "exception",
    "field": "className"
  },
  "error.message": {
    "$resolver": "exception",
    "field": "message"
  },
  "error.stack_trace": {
    "$resolver": "exception",
    "field": "stackTrace",
    "stackTrace": {
      "stringified": true
    }
  }
}
```

example of how the formatted log event should look like?

{
	"@timestamp": "2024-05-26T10:52:56.100Z",	"ecs.version": "1.2.0","log.level": "INFO",	"message": {"appId":"1234", "action":"Payment Received"}, "process.thread.name": "http-nio-0.0.0.0-59078-exec-1","log.logger": "com.example"
}

**Comment by vy** [comment]
@pSinghDelaplex, could you also

1. share the `logger.info("foo bar")` call that you do? That is, how do you pass the `{"appId":"1234", "action":"Payment Received"}` JSON?
2. Do you use SLF4J or Log4j API for logging?

**Comment by pSinghDelaplex** [comment]
Hi @vy 

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

private static final Logger LOGGER = LogManager.getLogger();
LOGGER.info(message);

public class Message<T> implements Serializable {
  private String appId;
  private String action;
}

2. SLF4J for logging

**Comment by vy** [comment]
@pSinghDelaplex, there are several things, if I may say, _wrong_ with your setup. I will try to explain them.

### `message` resolver configuration doesn't have a `field` parameter

You configure JTL as follows:

```
        JsonTemplateLayout:
          eventTemplateUri: classpath:EcsLayout.json
          eventTemplateAdditionalField:
            - key: "message"
              value: '{"$resolver": "message", "field": "name"}'
              format: "JSON"
```

See the `'{"$resolver": "message", "field": "name"}'` part? `message` resolver configuration doesn't accept a `field` parameter. Please consult to [the `message` resolver documentation](https://logging.apache.org/log4j/2.x/manual/json-template-layout.html#event-template-resolver-message) for further details.

As a matter of fact, for your needs, you need a `eventTemplateAdditionalField`. The plain `EcsLayout.json` is just fine, which is the default, hence, you don't even need to provide it:

```
        JsonTemplateLayout: {}
```

And you're good to go.

### Logging custom objects

Your `Message` needs to implement `org.apache.logging.log4j.message.MultiformatMessage` interface:

```
public class MyMessage implements MultiformatMessage {

    private static final String[] FORMATS = {"JSON"};

    private final String appId;

    private final String action;

    public String getFormattedMessage() {
        // Encode this instance to JSON and return it.
        // JTL won't magically encode it to JSON, you must yourself encode it here!
    }

    @Override
    public String[] getFormats() {
        return FORMATS;
    }

}
```

But I would advise you something simpler:

```
import org.apache.logging.log4j.message.StringMapMessage;

LOGGER.info(new StringMapMessage()
        .with("appId", appId)
        .with("action", action));
```
